language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: "h9UPimAbNzv+HsBAvreo5e+XmAfEyxvwn3ULtBv16LbuO+PikfONMZI/lfz+HlUKgEM5Pr+Y4v17OFu9P5CiDIb3qoIPqKGMY5TGOGaTc1tNdFSRrJ7bG3BejYJdooYIib4HQ5Qp0JWW0QL4vwR0SnFfgRnnJUSwp6rc1SOX/EA0PrmhubPB6Y+00MSFc+cNj31iZ+dFJ8ziJ+loSEossswauH9s0gdOxNAGH7CjP8SBH3RxxgNnkMtB6gBdSG3GfU9yQ5a920BBo+C8i9v3rRo2aF7QQiDrUy3lvmQNzga7mjikkDo3hKdWQfm0Nm8zhWfOWbTxuIwc98PySHOpOlO0VSA2EaKKqSwSwDt6UXSWeKmKjH4HyhWWS6Y7mHpyxCOgo1mOvOz0dRYDB0LAsv8ZfE4Srk3Snp+bVLVAijT6tErO56ZsLSFDVbdCNRLlLnKFo9guYRuMYDNymfwDBcZg4Qut0OdBx8hwse/x9tCXALyAOUDG6afLyAvnOX7m2gDvbTNFnyBB0iFS8bR+r4qdqZY6XR/tDrqy0+9OoppFbS2O4+Jo3RDkcb1PmotvWxaXCgpY67bugIbui1TiAx0t+h9CmWjgKts2cz7yZuQZTShbqNfOLsVbYJ/JyjElOBFSWvOp3UN3H1HSdwb0TUggegs7lG9S67kFNpwvHPY="
  - secure: "KoSNL0pmtMmh+0M322CJ99QFWilw/h/DRu8AtzSJKJ2tsr0JQnWD6ex3bo9+BqiO5Ao/odtuIvgHHhgL/CNqfuvLkFEGqv7BK0CsNsXECg8UVtcZa2mfFWx6mWSGQkGYm3gx+JAK4Keh62nh9LYP8ws6prds3HNxOQuBUGIaOD81PUqmXy5q9Owj7jKX7aOSp2RI14yZgAqdmBWQbMqGhjdzFNrvev5dz0+5R1C5LZm/FgmlcyDMPjKmrlAjvztGy5QkM162UydxWNIV3LV9uXGBAHg+yP8ba21MYhEPbAV5BMiGAHSxffkq27WMV+5cQMJgHH9IjcNNjTkg1bv3Ps4f+jlI0sUJBlFC2jXE9MqNtjtK+Doz01vELFSEV/M/oDkMPppjKAVsKmWD9ZsD1qTixVVmlSfsDOX+z3C2ejzX4yBb17Ejs5xFggtCKGZyXKynWHUqEa9eWfWNIWlomhBSKoYdpY/LrqaY/HtvzfULRgm4Ww1Mu07omnIaAnAmmZDMlX6k8UrWSXe9lp7e8uhjhUhz6IW+KaXsZzoufiarANM1GDZFJP7Nb1k3uXb/oXlHrN6755InmGBCoHUp8XTkgfLyaCtfUCj3ZfeIYnH/YQy0S4NO49C1eDr5BigkFPOHQfdHMPSW4C/VEKhRXenWDLhVPYSmAlCKtUncleo="
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: hQHAfWZAl8qNgQitOIeFf9cJOGWIVIw7mx02Lj3CW+f/tc8nGemXGJ9OMH70dlqf4k7ULO8VRECbUpthAuQRtZbrKWBCRvqeav6mUl0696Y45AMLEPGeLtP8Ri0V71Sw9aPcxYvswzgaBC8/25wizraSSbH4KXxbH+ksWZz2W8+ic6/W12UAg2DWdzufkTo+v+9A06ZQ5G4ct896CqUc2jcqLAat8Y/wsllp8T/yp03/EHWQ1VmjjWAyqXZzlnh98SONA37uPPHzh358OV2c1Wzs7OX5h0OTKoMoQ0WKYo+R1o4mdk83o15tr9YW1HG3a0mVCpGdDMcRyxFdKKg1MtwZymHghYA/2Ts3ht5gtrHDgDZVn0fjWQQN8yLZf6HqP9zhRBQY4tY8HojK9jffI/eMicX8Js3TjPQTmUjO305pr9mweXAtLp26qsjem2BVPSfC8X+IO9UjMUpnfQvMaAT9+tMuTho5NnSnCnF4+2GzHVZLwXfr21U2i2M4W0HrieDSPHL3/mXRB8m9QPTimVHGPkAy2aLA/7fsnkI4C55FaoXshmNqQhGXTloLqc0IkL7Q9xUIxuGh5ABh1Kx9w2Hif/3AjRYHXCclyVK3H2JizMTWvpwThn9tAccKwRpZhsIzh+XV9W2Xf75pqQtBm7ptxszLmsdcWMa9MLO8D18=
  on:
    branch: master
    repo: plepers/nanogl-primitives-2d
